### ISSUE TITLE
I don't quite understand how this mod work

### ISSUE THREAD

**Issue by Snogard** [Faeryn/Outward_LegacyUpgrade#1]
Sorry to bother you here, but as the title says i need some info on the mod.
I'm testing it on a mining pickaxe and so far i managed to enchant it and to bound the item to me with a legacy chest.
Toggling the details panel it says Tenuos bond with [my characater name], progress value of 0 and the id of my character and the legacy chest. I tried leaving the pickaxe in the chest for a in game week and the progress value still sits at 0. 
Am i missing something?

PS: i suggest you to update the readme with more detailed instructions, and thanks for your amazing work!

**Comment by Faeryn** [comment]
You have to have it equipped while you do things in the world (for example deal damage to mobs).
The "vagueness" and lack of guide is intentional: I'm following the Outward way!

**Comment by Snogard** [comment]
Thanks for the tip then!

**Comment by Raziel-Soulshadow** [comment]
Not sure if anyone will see this going forward other than the author (as it's buried in a closed issue), buuuut if you're like me and looking for any help possible, extra pro-tip; You actually have to press the T (or Y button, or whatever you have set to Take All for containers) once it's enchanted and in the legacy chest to bind it. My buddy and I thought it was broken cause of this, couldn't figure out why it wasn't changing from unbound when stuck in the chest... even tried leaving it in there and reloading.

Amazing mod mind you; Having a way to legitimately build Legacy Equipment in game -- as opposed to creating a new character, speed-running the chest, and then dropping it over via Split Multiplayer -- is amazing and feels much better AND fairer.
